/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file mega_moe_tiling_key.h
 * \brief
 */

#ifndef __OP_KERNEL_MEGA_MOE_TILING_KEY_H__
#define __OP_KERNEL_MEGA_MOE_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"
#include "mega_moe_tiling_a2a3.h"

namespace Mc2Tiling {

ASCENDC_TPL_ARGS_DECL(MegaMoe,
    ASCENDC_TPL_BOOL_DECL(TPL_IS_TRANSPOSE_W1, 0, 1),
    ASCENDC_TPL_BOOL_DECL(TPL_IS_TRANSPOSE_W2, 0, 1),
    ASCENDC_TPL_UINT_DECL(TPL_QUANT_MODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        MEGA_MOE_QUANT_MODE_NO_QUANT, MEGA_MOE_QUANT_MODE_PER_TENSOR),
    ASCENDC_TPL_UINT_DECL(TPL_QUANT_OUT_TYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        MEGA_MOE_QUANT_OUT_TYPE_UNDEFINED, MEGA_MOE_QUANT_OUT_TYPE_INT8,
        MEGA_MOE_QUANT_OUT_TYPE_INT4),
    ASCENDC_TPL_UINT_DECL(TPL_ARCH, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
        SOC_ASCEND910B, SOC_ASCEND910_93),
);

ASCENDC_TPL_SEL(
    // Quant path (PER_TENSOR): both A2 (910B) and A3 (910_93).
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_BOOL_SEL(TPL_IS_TRANSPOSE_W1, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_IS_TRANSPOSE_W2, 0),
        ASCENDC_TPL_UINT_SEL(TPL_QUANT_MODE, ASCENDC_TPL_UI_LIST,
            MEGA_MOE_QUANT_MODE_PER_TENSOR),
        ASCENDC_TPL_UINT_SEL(TPL_QUANT_OUT_TYPE, ASCENDC_TPL_UI_LIST,
            MEGA_MOE_QUANT_OUT_TYPE_INT8),
        ASCENDC_TPL_UINT_SEL(TPL_ARCH, ASCENDC_TPL_UI_LIST, SOC_ASCEND910B, SOC_ASCEND910_93),
        ASCENDC_TPL_TILING_STRUCT_SEL(MegaMoeTilingDataQuant)
    ),
    // Non-quant path: both A2 (910B) and A3 (910_93).
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_BOOL_SEL(TPL_IS_TRANSPOSE_W1, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_IS_TRANSPOSE_W2, 0, 1),
        ASCENDC_TPL_UINT_SEL(TPL_QUANT_MODE, ASCENDC_TPL_UI_LIST,
            MEGA_MOE_QUANT_MODE_NO_QUANT),
        ASCENDC_TPL_UINT_SEL(TPL_QUANT_OUT_TYPE, ASCENDC_TPL_UI_LIST,
            MEGA_MOE_QUANT_OUT_TYPE_UNDEFINED),
        ASCENDC_TPL_UINT_SEL(TPL_ARCH, ASCENDC_TPL_UI_LIST, SOC_ASCEND910B, SOC_ASCEND910_93),
        ASCENDC_TPL_TILING_STRUCT_SEL(MegaMoeTilingDataNonQuant)
    ),
);

} // namespace Mc2Tiling

#endif // __OP_KERNEL_MEGA_MOE_TILING_KEY_H__
